version: "3.7"

services:
  player1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - KAFKA_URL=kafka:9092
      - PLAYER_ID=player1
      - MODE=AUTOMATIC
    depends_on:
      - kafka
  player2:
    build: .
    ports:
      - "8081:8080"
    environment:
      - KAFKA_URL=kafka:9092
      - PLAYER_ID=player2
      - MODE=AUTOMATIC
    depends_on:
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    depends_on:
      - zookeeper
